### PR TITLE
[DD-1211] Add Json as new storage type

### PR DESCRIPTION
**Pull request by knutwalker**

### CODE REVIEW

**Comment by chrode** [comment]
test this please

**Comment by knutwalker** [comment]
I see. Don't we have this automatically added? Also, `grunt copyright:ensure` doesn't change anything.

**Comment by chrode** [comment]
Grunt build is adding the information locally.

**Comment by knutwalker** [comment]
I now have some test failures as well, gonna investigate this.

**Comment by knutwalker** [comment]
Ok, I'm pretty sure we ran those tests as well, but looking at the errors it is unlikely that it would have succeeded. Gonna patch the tests first, sorry about that.

**Comment by knutwalker** [comment]
@chrode Ok, now all tests should be fixed, licene added, etc.

**Pull request merged**
